const Food = [
    {
        id:1,
        name:'Apollo',
        category:'Cardiology',
        img:'img/clinic5.jpg',
        price:'5+',
    },
    {
        id:2,
        name:'Apollo',
        category:'Neurology',
        img:'img/doctor.jpg',
        price:"4+"
    },
    {
        id:3,
        name:'Apollo',
        category:'gastroenterology',
        img:'img/clinic5.jpg',
        price:"3+"
    },
    {
        id:4,
        name:'Apollo',
        category:'orthopaedic',
        img:'img/doctor.jpg',
        price:"5+"
    },
    {
        id:5,
        name:'Apollo',
        category:'Oncology',
        img:'img/doctor.jpg',
        price:"5+"
    },
    {
        id:6,
        name:'Apollo',
        category:'Gynecology',
        img:'img/clinic5.jpg',
        price:"5+"
    },
    {
        id:7,
        name:'Apollo',
        category:'Dermatology',
        img:'img/doctor.jpg',
        price:"5+"
    },
    {
        id:8,
        name:'Apollo',
        category:'Ophthalmology',
        img:'img/clinic5.jpg',
        price:"5+"
    },
    {
        id:9,
        name:'Apollo',
        category:'Pediatrics',
        img:'img/doctor.jpg',
        price:"5+"
    },
    {
        id:10,
        name:'Apollo',
        category:'Endocrinology',
        img:'img/clinic5.jpg',
        price:"5+"
    },
    {
        id:11,
        name:'Apollo',
        category:'Nephrology',
        img:'img/clinic5.jpg',
        price:"5+"
    },
    {
        id:12,
        name:'Apollo',
        category:'Pulmonology',
        img:'img/clinic5.jpg',
        price:"5+"
    },
   
]

export default Food